/*
 * To change this license FBackground, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebill;

import static ebill.FunctionGetSetData.lastKode;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import style.FBackground;
import style.FButtonFunction;
import style.FExitBackground;
import style.FHeaderBackground;
import style.FHeaderTable;
import style.FTable;

/**
 *
 * @author Fikri-Falndi
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new FBackground();
        jPanel1 = new FHeaderBackground();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelKartuBarang = new FExitBackground();
        panelBarangBaru = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtKodeBarang = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        cmbSatuan = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        color1 = new Color(84, 116, 177);
        color2 = new Color(84, 139, 215);
        btnKembaliBarang = new FButtonFunction(color1, color2);
        color1 = new Color(0, 74, 138);
        color2 = new Color(0, 137, 194);
        btnSimpan = new FButtonFunction(color1, color2);
        color1 = new Color(230, 33, 42);
        color2 = new Color(190, 0, 0);
        btnBatal = new FButtonFunction(color1, color2);
        color1 = new Color(167, 209, 219);
        color2 = new Color(167, 180, 255);
        btnInputBarang = new FButtonFunction(color1, color2);
        color1 = new Color(60, 143, 159);
        color2 = new Color(60, 171, 179);
        btnListBarang = new FButtonFunction(color1, color2);
        color1 = new Color(152, 190, 215);
        color2 = new Color(152, 150, 255);
        btnStockBarang = new FButtonFunction(color1, color2);
        panelStokBaru = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtNamaBrgStock = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtStMasuk = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtKetStock = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtSatuanStock = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtStKeluar = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        color1 = new Color(230, 33, 42);
        color2 = new Color(190, 0, 0);
        btnHapusBarang = new FButtonFunction(color1, color2);
        color1 = new Color(60, 143, 159);
        color2 = new Color(60, 171, 179);
        btnEditBarang = new FButtonFunction(color1, color2);
        color1 = new Color(0, 74, 138);
        color2 = new Color(0, 137, 194);
        btnCetakBarang = new FButtonFunction(color1, color2);
        panelHome = new FExitBackground();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        color1 = new Color(167, 209, 219);
        color2 = new Color(167, 180, 255);
        jButton5 = new style.FButtonHome(color1, color2, 5, 16);
        color1 = new Color(60, 143, 159);
        color2 = new Color(60, 171, 179);
        jButton6 = new style.FButtonHome(color1, color2, 6, 16);
        color1 = new Color(82, 162, 197);
        color2 = new Color(82, 190, 209);
        jButton2 = new style.FButtonHome(color1, color2, 2, 16);
        color1 = new Color(152, 190, 215);
        color2 = new Color(152, 150, 255);
        jButton4 = new style.FButtonHome(color1, color2, 4, 16);
        color1 = new Color(84, 116, 177);
        color2 = new Color(84, 139, 215);
        jButton3 = new style.FButtonHome(color1, color2, 3, 16);
        color1 = new Color(230, 33, 42);
        color2 = new Color(190, 0, 0);
        jButton7 = new style.FButtonHome(color1, color2, 0, 20);
        color1 = new Color(0, 74, 138);
        color2 = new Color(0, 137, 194);
        jButton1 = new style.FButtonHome(color1,color2,1,25);
        panelFaktur = new FExitBackground();
        panelFakturBaru = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        color1 = new Color(152, 190, 215);
        color2 = new Color(152, 150, 255);
        btnList = new FButtonFunction(color1, color2);
        color1 = new Color(60, 143, 159);
        color2 = new Color(60, 171, 179);
        btnBaru = new FButtonFunction(color1, color2);
        color1 = new Color(0, 74, 138);
        color2 = new Color(0, 137, 194);
        btnEdit = new FButtonFunction(color1, color2);
        color1 = new Color(230, 33, 42);
        color2 = new Color(190, 0, 0);
        btnHapus = new FButtonFunction(color1, color2);
        color1 = new Color(84, 116, 177);
        color2 = new Color(84, 139, 215);
        jButton12 = new FButtonFunction(color1, color2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel5.setPreferredSize(new java.awt.Dimension(1343, 740));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1343, 50));

        jLabel1.setFont(new java.awt.Font("Humanst521 BT", 2, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 251, 253));
        jLabel1.setText("PRASETYO GYSPUM");

        jLabel2.setFont(new java.awt.Font("Humanst521 BT", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 93, 136));
        jLabel2.setText("LOGO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1048, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelKartuBarang.setBackground(new java.awt.Color(255, 255, 255));
        panelKartuBarang.setMinimumSize(new java.awt.Dimension(1024, 600));
        panelKartuBarang.setPreferredSize(new java.awt.Dimension(1343, 652));
        panelKartuBarang.setLayout(null);

        panelBarangBaru.setBackground(new java.awt.Color(255, 255, 255));
        panelBarangBaru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(82, 162, 197)));
        panelBarangBaru.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel30.setText("Kode Barang");
        panelBarangBaru.add(jLabel30);
        jLabel30.setBounds(20, 20, 120, 23);

        jLabel31.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel31.setText("Nama Barang");
        panelBarangBaru.add(jLabel31);
        jLabel31.setBounds(20, 50, 120, 23);

        jLabel33.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel33.setText("Satuan");
        panelBarangBaru.add(jLabel33);
        jLabel33.setBounds(20, 80, 100, 23);

        txtNamaBarang.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelBarangBaru.add(txtNamaBarang);
        txtNamaBarang.setBounds(150, 50, 250, 26);

        txtKodeBarang.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        txtKodeBarang.setEnabled(false);
        panelBarangBaru.add(txtKodeBarang);
        txtKodeBarang.setBounds(150, 20, 250, 26);

        txtHarga.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelBarangBaru.add(txtHarga);
        txtHarga.setBounds(990, 20, 250, 26);

        jLabel39.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel39.setText("Keterangan");
        panelBarangBaru.add(jLabel39);
        jLabel39.setBounds(860, 50, 100, 23);

        jLabel40.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel40.setText("Harga");
        panelBarangBaru.add(jLabel40);
        jLabel40.setBounds(860, 20, 100, 23);

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(2);
        jScrollPane7.setViewportView(txtKeterangan);

        panelBarangBaru.add(jScrollPane7);
        jScrollPane7.setBounds(990, 50, 250, 60);

        cmbSatuan.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Bh", "Btg", "Dus", "Kg", "Klng", "Lbr", "Pcs", "Roll", "Zak" }));
        panelBarangBaru.add(cmbSatuan);
        cmbSatuan.setBounds(150, 80, 90, 25);

        panelKartuBarang.add(panelBarangBaru);
        panelBarangBaru.setBounds(50, 160, 1260, 125);
        panelBarangBaru.setVisible(false);

        jLabel17.setFont(new java.awt.Font("Humanst521 BT", 0, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(2, 93, 136));
        jLabel17.setText("E-Bill");
        panelKartuBarang.add(jLabel17);
        jLabel17.setBounds(50, 30, 160, 50);

        jLabel18.setFont(new java.awt.Font("Humanst521 BT", 2, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("List Barang");
        panelKartuBarang.add(jLabel18);
        jLabel18.setBounds(50, 120, 200, 30);

        jLabel19.setFont(new java.awt.Font("Humanst521 BT", 0, 26)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(2, 93, 136));
        jLabel19.setText("Kartu Barang");
        panelKartuBarang.add(jLabel19);
        jLabel19.setBounds(50, 90, 150, 30);

        jScrollPane6.setBackground(new java.awt.Color(2, 93, 135));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Barang", "Nama Barang", "Tipe", "Keterangan"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(240, 240, 240));
        jTable3.setRowHeight(25);
        jScrollPane6.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(50);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(50);
        }
        column = jTable3.getColumnCount();
        for(int i=0; i < column; i++){
            jTable3.getColumnModel().getColumn(i).setCellRenderer(new FTable());
            jTable3.getColumnModel().getColumn(i).setHeaderRenderer(new FHeaderTable());
        }

        panelKartuBarang.add(jScrollPane6);
        jScrollPane6.setBounds(50, 160, 1260, 470);

        btnKembaliBarang.setText("KEMBALI");
        btnKembaliBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliBarangActionPerformed(evt);
            }
        });
        panelKartuBarang.add(btnKembaliBarang);
        btnKembaliBarang.setBounds(50, 640, 140, 30);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelKartuBarang.add(btnSimpan);
        btnSimpan.setBounds(1170, 270, 140, 30);

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        panelKartuBarang.add(btnBatal);
        btnBatal.setBounds(1020, 270, 140, 30);

        btnInputBarang.setText("INPUT BARU");
        btnInputBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputBarangActionPerformed(evt);
            }
        });
        panelKartuBarang.add(btnInputBarang);
        btnInputBarang.setBounds(870, 640, 140, 30);

        btnListBarang.setText("LIST BARANG");
        btnListBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListBarangActionPerformed(evt);
            }
        });
        panelKartuBarang.add(btnListBarang);
        btnListBarang.setBounds(1020, 105, 140, 30);

        btnStockBarang.setText("STOCK BARANG");
        btnStockBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockBarangActionPerformed(evt);
            }
        });
        panelKartuBarang.add(btnStockBarang);
        btnStockBarang.setBounds(1170, 105, 140, 30);

        panelStokBaru.setBackground(new java.awt.Color(255, 255, 255));
        panelStokBaru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(82, 162, 197)));
        panelStokBaru.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel32.setText("Kode Barang");
        panelStokBaru.add(jLabel32);
        jLabel32.setBounds(20, 20, 120, 23);

        jLabel34.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel34.setText("Nama Barang");
        panelStokBaru.add(jLabel34);
        jLabel34.setBounds(20, 50, 120, 23);

        jLabel36.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel36.setText("Tanggal");
        panelStokBaru.add(jLabel36);
        jLabel36.setBounds(450, 20, 120, 23);

        jLabel37.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel37.setText("Stok Masuk");
        panelStokBaru.add(jLabel37);
        jLabel37.setBounds(450, 50, 90, 23);

        txtNamaBrgStock.setEditable(false);
        txtNamaBrgStock.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelStokBaru.add(txtNamaBrgStock);
        txtNamaBrgStock.setBounds(150, 50, 250, 26);

        txtTanggal.setEditable(false);
        txtTanggal.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelStokBaru.add(txtTanggal);
        txtTanggal.setBounds(580, 20, 250, 26);

        txtStMasuk.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelStokBaru.add(txtStMasuk);
        txtStMasuk.setBounds(580, 50, 100, 26);

        txtKetStock.setColumns(20);
        txtKetStock.setRows(3);
        jScrollPane9.setViewportView(txtKetStock);

        panelStokBaru.add(jScrollPane9);
        jScrollPane9.setBounds(990, 20, 250, 60);

        jLabel42.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel42.setText("Keterangan");
        panelStokBaru.add(jLabel42);
        jLabel42.setBounds(860, 20, 120, 23);

        jLabel35.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel35.setText("Satuan");
        panelStokBaru.add(jLabel35);
        jLabel35.setBounds(20, 80, 120, 23);

        txtSatuanStock.setEditable(false);
        txtSatuanStock.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelStokBaru.add(txtSatuanStock);
        txtSatuanStock.setBounds(150, 80, 100, 26);

        txtStock.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelStokBaru.add(txtStock);
        txtStock.setBounds(150, 110, 100, 26);

        jLabel43.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel43.setText("Stok");
        panelStokBaru.add(jLabel43);
        jLabel43.setBounds(20, 110, 120, 23);

        jLabel44.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel44.setText("Stok Keluar");
        panelStokBaru.add(jLabel44);
        jLabel44.setBounds(450, 80, 90, 23);

        txtStKeluar.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelStokBaru.add(txtStKeluar);
        txtStKeluar.setBounds(580, 80, 100, 26);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        panelStokBaru.add(jComboBox2);
        jComboBox2.setBounds(150, 20, 250, 25);

        panelKartuBarang.add(panelStokBaru);
        panelStokBaru.setBounds(50, 160, 1260, 150);
        panelStokBaru.setVisible(false);

        btnHapusBarang.setText("HAPUS");
        panelKartuBarang.add(btnHapusBarang);
        btnHapusBarang.setBounds(720, 640, 140, 30);

        btnEditBarang.setText("EDIT");
        btnEditBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBarangActionPerformed(evt);
            }
        });
        panelKartuBarang.add(btnEditBarang);
        btnEditBarang.setBounds(1020, 640, 140, 30);

        btnCetakBarang.setText("CETAK");
        btnCetakBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakBarangActionPerformed(evt);
            }
        });
        panelKartuBarang.add(btnCetakBarang);
        btnCetakBarang.setBounds(1170, 640, 140, 30);

        panelKartuBarang.setVisible(false);

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setMinimumSize(new java.awt.Dimension(1024, 600));
        panelHome.setPreferredSize(new java.awt.Dimension(1343, 652));
        panelHome.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Humanst521 BT", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 93, 136));
        jLabel3.setText("E-Bill");
        panelHome.add(jLabel3);
        jLabel3.setBounds(50, 30, 160, 50);

        jLabel20.setFont(new java.awt.Font("Humanst521 BT", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setLabelFor(jButton1);
        jLabel20.setText("Invoice");
        panelHome.add(jLabel20);
        jLabel20.setBounds(90, 260, 80, 20);

        jLabel21.setFont(new java.awt.Font("Humanst521 BT", 1, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setLabelFor(jButton4);
        jLabel21.setText("2500");
        panelHome.add(jLabel21);
        jLabel21.setBounds(810, 470, 60, 21);

        jLabel22.setFont(new java.awt.Font("Humanst521 BT", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setLabelFor(jButton2);
        jLabel22.setText("Faktur");
        panelHome.add(jLabel22);
        jLabel22.setBounds(485, 260, 50, 21);

        jLabel23.setFont(new java.awt.Font("Humanst521 BT", 1, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setLabelFor(jButton5);
        jLabel23.setText("300");
        panelHome.add(jLabel23);
        jLabel23.setBounds(1230, 260, 50, 21);

        jLabel24.setFont(new java.awt.Font("Humanst521 BT", 2, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Jam");
        panelHome.add(jLabel24);
        jLabel24.setBounds(1070, 350, 210, 60);

        jLabel25.setFont(new java.awt.Font("Humanst521 BT", 2, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Tanggal");
        panelHome.add(jLabel25);
        jLabel25.setBounds(1040, 410, 240, 29);

        jLabel26.setFont(new java.awt.Font("Humanst521 BT", 0, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setLabelFor(jButton3);
        jLabel26.setText("Penjualan");
        panelHome.add(jLabel26);
        jLabel26.setBounds(700, 260, 80, 21);

        jLabel27.setFont(new java.awt.Font("Humanst521 BT", 0, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setLabelFor(jButton4);
        jLabel27.setText("Kartu Barang");
        panelHome.add(jLabel27);
        jLabel27.setBounds(485, 470, 100, 21);

        jLabel28.setFont(new java.awt.Font("Humanst521 BT", 0, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setLabelFor(jButton5);
        jLabel28.setText("Klien");
        panelHome.add(jLabel28);
        jLabel28.setBounds(920, 260, 50, 21);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/image/user.png"))); // NOI18N
        panelHome.add(jButton5);
        jButton5.setBounds(900, 90, 400, 200);

        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/image/clock-circular-outline.png"))); // NOI18N
        jButton6.setText("          ");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelHome.add(jButton6);
        jButton6.setBounds(900, 300, 400, 200);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/image/list.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelHome.add(jButton2);
        jButton2.setBounds(470, 90, 205, 200);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/image/trolley.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelHome.add(jButton4);
        jButton4.setBounds(470, 300, 420, 200);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/image/line-chart.png"))); // NOI18N
        panelHome.add(jButton3);
        jButton3.setBounds(685, 90, 205, 200);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/image/power-button-sign.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelHome.add(jButton7);
        jButton7.setBounds(1200, 540, 100, 100);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/style/image/add-documents.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelHome.add(jButton1);
        jButton1.setBounds(50, 90, 410, 410);

        //panelHome.setVisible(false);

        panelFaktur.setBackground(new java.awt.Color(255, 255, 255));
        panelFaktur.setMinimumSize(new java.awt.Dimension(1024, 600));
        panelFaktur.setPreferredSize(new java.awt.Dimension(1343, 652));
        panelFaktur.setLayout(null);

        panelFakturBaru.setBackground(new java.awt.Color(255, 255, 255));
        panelFakturBaru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(82, 162, 197)));
        panelFakturBaru.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel7.setText("Metode Pembayaran");
        panelFakturBaru.add(jLabel7);
        jLabel7.setBounds(810, 80, 150, 23);

        jLabel8.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel8.setText("No. Kwitansi");
        panelFakturBaru.add(jLabel8);
        jLabel8.setBounds(20, 20, 120, 23);

        jLabel9.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel9.setText("Nama Pembeli");
        panelFakturBaru.add(jLabel9);
        jLabel9.setBounds(20, 50, 120, 23);

        jLabel10.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel10.setText("Alamat");
        panelFakturBaru.add(jLabel10);
        jLabel10.setBounds(20, 80, 120, 23);

        jLabel11.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel11.setText("Tanggal Kwitansi");
        panelFakturBaru.add(jLabel11);
        jLabel11.setBounds(810, 20, 120, 23);

        jLabel12.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel12.setText("Tanggal Jatuh Tempo");
        panelFakturBaru.add(jLabel12);
        jLabel12.setBounds(810, 50, 150, 23);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(3);
        jScrollPane3.setViewportView(jTextArea1);

        panelFakturBaru.add(jScrollPane3);
        jScrollPane3.setBounds(150, 80, 250, 60);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelFakturBaru.add(jTextField3);
        jTextField3.setBounds(150, 20, 250, 26);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelFakturBaru.add(jTextField4);
        jTextField4.setBounds(980, 20, 250, 26);

        jTextField5.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelFakturBaru.add(jTextField5);
        jTextField5.setBounds(980, 50, 250, 26);

        jComboBox1.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pililh-", "Cash", "Transfer" }));
        panelFakturBaru.add(jComboBox1);
        jComboBox1.setBounds(980, 80, 250, 30);

        jScrollPane4.setBackground(new java.awt.Color(2, 93, 135));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Barang", "Nama Barang", "Satuan", "Banyak", "Harga Satuan", "Harga Jumlah"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(240, 240, 240));
        jTable2.setRowHeight(20);
        jScrollPane4.setViewportView(jTable2);
        column = jTable2.getColumnCount();
        for(int i=0; i < column; i++){
            jTable2.getColumnModel().getColumn(i).setCellRenderer(new FTable());
            jTable2.getColumnModel().getColumn(i).setHeaderRenderer(new FHeaderTable());
        }

        panelFakturBaru.add(jScrollPane4);
        jScrollPane4.setBounds(0, 170, 1260, 220);

        jLabel13.setFont(new java.awt.Font("Humanst521 BT", 2, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 115, 175));
        jLabel13.setText("Detail Barang");
        panelFakturBaru.add(jLabel13);
        jLabel13.setBounds(20, 140, 100, 30);

        jTextField6.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelFakturBaru.add(jTextField6);
        jTextField6.setBounds(150, 400, 250, 26);

        jLabel14.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel14.setText("Tanda Tangan");
        panelFakturBaru.add(jLabel14);
        jLabel14.setBounds(20, 400, 120, 23);

        jTextField7.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        panelFakturBaru.add(jTextField7);
        jTextField7.setBounds(150, 430, 250, 26);

        jLabel15.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel15.setText("Jabatan");
        panelFakturBaru.add(jLabel15);
        jLabel15.setBounds(20, 430, 120, 23);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(3);
        jScrollPane5.setViewportView(jTextArea2);

        panelFakturBaru.add(jScrollPane5);
        jScrollPane5.setBounds(920, 400, 310, 60);

        jLabel16.setFont(new java.awt.Font("Humanst521 BT", 0, 16)); // NOI18N
        jLabel16.setText("Keterangan");
        panelFakturBaru.add(jLabel16);
        jLabel16.setBounds(810, 400, 120, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-" }));
        panelFakturBaru.add(jComboBox3);
        jComboBox3.setBounds(150, 50, 250, 25);

        panelFaktur.add(panelFakturBaru);
        panelFakturBaru.setBounds(50, 160, 1260, 470);
        panelFakturBaru.setVisible(false);

        jLabel4.setFont(new java.awt.Font("Humanst521 BT", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 93, 136));
        jLabel4.setText("E-Bill");
        panelFaktur.add(jLabel4);
        jLabel4.setBounds(50, 30, 160, 50);

        jLabel5.setFont(new java.awt.Font("Humanst521 BT", 2, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("List Faktur");
        panelFaktur.add(jLabel5);
        jLabel5.setBounds(50, 120, 100, 30);

        jLabel6.setFont(new java.awt.Font("Humanst521 BT", 0, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 93, 136));
        jLabel6.setText("Faktur");
        panelFaktur.add(jLabel6);
        jLabel6.setBounds(50, 90, 150, 30);

        jScrollPane2.setBackground(new java.awt.Color(2, 93, 135));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "No. Invoice", "Nama Pembeli", "Tanggal Cetak", "Jatuh Tempo", "Tanda Tangan Oleh"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(240, 240, 240));
        jTable1.setRowHeight(20);
        jScrollPane2.setViewportView(jTable1);
        column = jTable1.getColumnCount();
        for(int i=0; i < column; i++){
            jTable1.getColumnModel().getColumn(i).setCellRenderer(new FTable());
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(new FHeaderTable());
        }

        panelFaktur.add(jScrollPane2);
        jScrollPane2.setBounds(50, 160, 1260, 470);

        btnList.setText("LIST");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        panelFaktur.add(btnList);
        btnList.setBounds(1170, 105, 140, 30);

        btnBaru.setText("BARU");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });
        panelFaktur.add(btnBaru);
        btnBaru.setBounds(1020, 105, 140, 30);

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelFaktur.add(btnEdit);
        btnEdit.setBounds(1170, 640, 140, 30);

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        panelFaktur.add(btnHapus);
        btnHapus.setBounds(1020, 640, 140, 30);

        jButton12.setText("KEMBALI");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panelFaktur.add(jButton12);
        jButton12.setBounds(50, 640, 140, 30);

        panelFaktur.setVisible(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelKartuBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelKartuBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel5);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        final DateFormat dateFormatHours = new SimpleDateFormat("HH:mm:ss");
        final DateFormat dateFormatDates = new SimpleDateFormat("dd MMMM yyyy");
        final DateFormat dateFormatDate2 = new SimpleDateFormat("dd/MM/yyyy");

        new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                jLabel24.setText(dateFormatHours.format(date));
                jLabel25.setText(dateFormatDates.format(date));
            }
        }).start();

        Date date = new Date();
        txtTanggal.setText(dateFormatDate2.format(date));

        fc.getDataBarang(jTable3);
        fc.getKodeBarang(jComboBox2, "SELECT * FROM _barang");

        String lk = lastKode("SELECT * FROM _barang order by kode_barang desc limit 1");
        txtKodeBarang.setText(lk);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (panelFakturBaru.isVisible()) {
            jScrollPane2.setVisible(true);
            panelFakturBaru.setVisible(false);
            panelKartuBarang.setVisible(false);
            btnHapus.setVisible(true);
            btnEdit.setText("EDIT");
        } else {
            panelFaktur.setVisible(false);
            panelHome.setVisible(true);
            panelKartuBarang.setVisible(false);
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        jScrollPane2.setVisible(false);
        panelFakturBaru.setVisible(true);
        btnHapus.setVisible(false);
        btnEdit.setText("CETAK");
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        jScrollPane2.setVisible(true);
        panelFakturBaru.setVisible(false);
        btnHapus.setVisible(true);
        btnEdit.setText("EDIT");
    }//GEN-LAST:event_btnListActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        panelHome.setVisible(false);
        panelFaktur.setVisible(false);
        panelKartuBarang.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Exit exit = new Exit(this, rootPaneCheckingEnabled);
        exit.setLocationRelativeTo(null);
        exit.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnKembaliBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliBarangActionPerformed
        // TODO add your handling code here:
        panelHome.setVisible(true);
        panelFaktur.setVisible(false);
        panelKartuBarang.setVisible(false);
    }//GEN-LAST:event_btnKembaliBarangActionPerformed

    private void btnInputBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputBarangActionPerformed
        // TODO add your handling code here:
        jScrollPane6.setVisible(false);
        btnCetakBarang.setVisible(false);
        btnHapusBarang.setVisible(false);
        btnInputBarang.setVisible(false);
        btnEditBarang.setVisible(false);
        btnKembaliBarang.setVisible(false);
        if (panelBarang == 0) {
            panelBarangBaru.setVisible(true);
            panelStokBaru.setVisible(false);
            btnBatal.setBounds(1020, 295, 140, 30);
            btnSimpan.setBounds(1170, 295, 140, 30);
            batalBarang();
        } else if (panelBarang == 1) {
            btnBatal.setBounds(1020, 320, 140, 30);
            btnSimpan.setBounds(1170, 320, 140, 30);
            panelBarangBaru.setVisible(false);
            panelStokBaru.setVisible(true);
        }


    }//GEN-LAST:event_btnInputBarangActionPerformed

    private void btnListBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListBarangActionPerformed
        // TODO add your handling code here:
        panelBarang = 0;
        fc.getDataBarang(jTable3);
        jLabel18.setText("List Barang");
        kartuBarang();
    }//GEN-LAST:event_btnListBarangActionPerformed

    private void btnStockBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockBarangActionPerformed
        // TODO add your handling code here:
        panelBarang = 1;
        Object stock[] = {"No", "Kode Barang", "Nama Barang", "Satuan", "Tanggal", "Stok", "Masuk", "Keluar", "Total", "Keterangan"};
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null}
                },
                new String[]{
                    "No", "Kode Barang", "Nama Barang", "Satuan", "Tanggal", "Stok", "Masuk", "Keluar", "Total", "Keterangan"
                }
        ));
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(50);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(50);
        }
        column = jTable3.getColumnCount();
        for (int i = 0; i < column; i++) {
            jTable3.getColumnModel().getColumn(i).setCellRenderer(new FTable());
            jTable3.getColumnModel().getColumn(i).setHeaderRenderer(new FHeaderTable());
        }

        
        jLabel18.setText("Stock Barang");
        kartuBarang();
    }//GEN-LAST:event_btnStockBarangActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        kartuBarang();
        batalBarang();

    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (panelBarangBaru.isVisible()) {
            if (txtKodeBarang.equals("") || txtNamaBarang.equals("") || cmbSatuan.getSelectedIndex() == 0 || txtHarga.equals("") || txtKeterangan.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Form Data Tidak Boleh Kosong", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    String query = "INSERT INTO _barang VALUES('" + txtKodeBarang.getText() + "', '" + txtNamaBarang.getText() + "', '" + cmbSatuan.getSelectedItem() + "', '" + txtHarga.getText() + "', '" + txtKeterangan.getText() + "')";
                    fc.insertData(query);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                    fc.getDataBarang(jTable3);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan");
                }

            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBarangActionPerformed
        // TODO add your handling code here:
        jScrollPane6.setVisible(false);
        btnCetakBarang.setVisible(false);
        btnHapusBarang.setVisible(false);
        btnInputBarang.setVisible(false);
        btnEditBarang.setVisible(false);
        btnKembaliBarang.setVisible(false);
        if (panelBarang == 0) {

            panelBarangBaru.setVisible(true);
            panelStokBaru.setVisible(false);
            btnBatal.setBounds(1020, 295, 140, 30);
            btnSimpan.setBounds(1170, 295, 140, 30);
            jTable3.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                @Override
                public void valueChanged(ListSelectionEvent e) {
                    int selectRow = jTable3.getSelectedRow();
                    txtKodeBarang.setText(jTable3.getValueAt(selectRow, 1).toString());
                    txtNamaBarang.setText(jTable3.getValueAt(selectRow, 2).toString());
                    cmbSatuan.setSelectedItem(jTable3.getValueAt(selectRow, 3).toString());
                    txtHarga.setText(jTable3.getValueAt(selectRow, 4).toString());
                    txtKeterangan.setText(jTable3.getValueAt(selectRow, 5).toString());
                }
            });
        }
        System.out.println(panelBarang);

    }//GEN-LAST:event_btnEditBarangActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex() == 0) {
            txtNamaBrgStock.setText(null);
            txtSatuanStock.setText(null);
        } else {
            fc.setData(txtNamaBrgStock, txtSatuanStock, "SELECT * FROM _barang WHERE kode_barang='" + jComboBox2.getSelectedItem() + "'");
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void btnCetakBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakBarangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCetakBarangActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelHome.setVisible(false);
        panelFaktur.setVisible(true);
        panelKartuBarang.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {

            }
        });
    }//GEN-LAST:event_btnEditActionPerformed

    public void kartuBarang() {
        jScrollPane6.setVisible(true);
        panelBarangBaru.setVisible(false);
        btnCetakBarang.setVisible(true);
        btnHapusBarang.setVisible(true);
        btnInputBarang.setVisible(true);
        btnEditBarang.setVisible(true);
        btnKembaliBarang.setVisible(true);
    }

    public void batalBarang() {
        String lk = lastKode("SELECT * FROM _barang order by kode_barang desc limit 1");
        txtKodeBarang.setText(lk);
        txtNamaBarang.setText(null);
        cmbSatuan.setSelectedIndex(0);
        txtHarga.setText(null);
        txtKeterangan.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    int panelBarang = 0;
    FunctionGetSetData fc = new FunctionGetSetData();
    Color color1, color2;
    int column;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetakBarang;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditBarang;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusBarang;
    private javax.swing.JButton btnInputBarang;
    private javax.swing.JButton btnKembaliBarang;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnListBarang;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnStockBarang;
    private javax.swing.JComboBox cmbSatuan;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel panelBarangBaru;
    public javax.swing.JPanel panelFaktur;
    private javax.swing.JPanel panelFakturBaru;
    public javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelKartuBarang;
    private javax.swing.JPanel panelStokBaru;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextArea txtKetStock;
    private javax.swing.JTextArea txtKeterangan;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaBrgStock;
    private javax.swing.JTextField txtSatuanStock;
    private javax.swing.JTextField txtStKeluar;
    private javax.swing.JTextField txtStMasuk;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
